services:
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: paginacion
    volumes:
      - ./data:/var/lib/postgresql/data
